// Generated by CoffeeScript 1.12.4
var Event, didExit, isNodeJS;

isNodeJS = require("isNodeJS");

Event = require("eve");

module.exports = didExit = Event();

if (isNodeJS) {
  process.once("SIGINT", function() {
    return process.exit(130);
  });
  process.once("SIGTERM", function() {
    return process.exit(143);
  });
  process.once("exit", function(code) {
    var error;
    try {
      return didExit.emit(code);
    } catch (error1) {
      error = error1;
      console.log(code);
      return console.error(error);
    }
  });
}
